apiVersion: apps/v1
kind: Deployment
metadata:
  name: descheduler-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: descheduler-operator
  template:
    metadata:
      labels:
        name: descheduler-operator
    spec:
      serviceAccountName: descheduler-operator
      containers:
        - name: descheduler-operator
          # Replace this with the built image name
          image: skckadiyala/descheduler-operator:v0.0.3
          command:
          - descheduler-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "descheduler-operator"
