apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deschedulers.descheduler.axway.com
  namespace: {{ .Values.namespace }}
spec:
  group: descheduler.axway.com
  names:
    kind: Descheduler
    listKind: DeschedulerList
    plural: deschedulers
    singular: descheduler
  scope: Namespaced
  version: v1alpha1
