kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: descheduler-operator
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }} 
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: descheduler-operator
  apiGroup: rbac.authorization.k8s.io
